image: "julia:1"

variables:
  JULIA_DEPOT_PATH: "$CI_PROJECT_DIR/.julia/"

cache:
  paths:
    - .julia/

build:
  stage: build
  script:
    - julia -e 'using InteractiveUtils;
                versioninfo()'
    - julia --project -e 'using Pkg;
                          Pkg.update();
                          Pkg.instantiate();
                          using PuMaS;'
  only:
  - master
  - tags
  - external
  - pushes


test-core:
  stage: test
  variables:
    GROUP: "Core"
  script:
    - julia -e 'using InteractiveUtils;
                versioninfo()'
    - julia --project -e 'using Pkg;
                          Pkg.test("PuMaS"; coverage=true);'
  only:
  - master
  - tags
  - external
  - pushes


test-nca:
  stage: test
  variables:
    GROUP: "NCA"
  script:
    - julia -e 'using InteractiveUtils;
                versioninfo()'
    - julia --project -e 'using Pkg;
                          Pkg.test("PuMaS"; coverage=true);'
  only:
  - master
  - tags
  - external
  - pushes


test-nlme-ml1:
  stage: test
  variables:
    GROUP: "NLME_ML1"
  script:
    - julia -e 'using InteractiveUtils;
                versioninfo()'
    - julia --project -e 'using Pkg;
                          Pkg.test("PuMaS"; coverage=true);'
  only:
    - master
    - tags
    - external
    - pushes

test-nlme-ml2:
  stage: test
  variables:
    GROUP: "NLME_ML2"
  script:
    - julia -e 'using InteractiveUtils;
                versioninfo()'
    - julia --project -e 'using Pkg;
                          Pkg.test("PuMaS"; coverage=true);'
  only:
    - master
    - tags
    - external
    - pushes

test-nlme-bayes:
  stage: test
  variables:
    GROUP: "NLME_BAYES"
    BAYES_N: 100
  script:
    - julia -e 'using InteractiveUtils;
                versioninfo()'
    - julia --project -e 'using Pkg;
                          Pkg.test("PuMaS"; coverage=true);'
  only:
    - master
    - tags
    - external
    - pushes


test-features:
  stage: test
  variables:
    GROUP: "Features"
  script:
    - julia -e 'using InteractiveUtils;
                versioninfo()'
    - julia --project -e 'using Pkg;
                          Pkg.test("PuMaS"; coverage=true);'
  only:
  - master
  - tags
  - external
  - pushes

